version: "3.7"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./volume-data/redis:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      microservice-demo:
        aliases:
          - redis
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    volumes:
      - ./volume-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: tcb
      MYSQL_PASSWORD: password
    networks:
      microservice-demo:
        aliases:
          - mysql
#  config:
#    image: microservice/config
#    container_name: config
#    ports:
#      - 8761:8761
#    restart: always
#    networks:
#      microservice-demo:
#        aliases:
#          - config

# networking for the Redis container
networks:
  microservice-demo:
    external: true
