version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      system-demo:
        aliases:
          - zookeeper

  kafka-cluster:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    container_name: kafka-cluster
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-cluster:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      system-demo:
        aliases:
          - kafka-cluster

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka-cluster
    container_name: kafka-ui
    ports:
      - 8088:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-cluster:9092"
    networks:
      system-demo:
        aliases:
          - kafka-ui

  mysql:
    image: mysql:5.7.16
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      # Change directory path
      - /mnt/c/projects/microservice-lab/micro-services-lab/demo/etc/docker/volume-data/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "demo"
      MYSQL_PASSWORD: "demo"
    networks:
      system-demo:
        aliases:
          - mysql

networks:
  system-demo:
    external: false
