kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: default
  labels:
    app.kubernetes.io/part-of: infra
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: demo
            - name: MYSQL_PASSWORD
              value: demo
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
          terminationMessagePolicy: File
          image: >-
            mysql:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler