apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  selector:
    app: kafka-cluster
  ports:
    - protocol: TCP
      port: 29092
      name: TCP-29092
      targetPort: 29092
    - protocol: TCP
      name: TCP-9092
      port: 9092
      targetPort: 9092