kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: default
  labels:
    app.kubernetes.io/part-of: infra
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: zookeeper
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            confluentinc/cp-zookeeper:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler